# db-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_NAME: your_database_name
  DB_USER: your_database_user
  DB_PASSWORD: your_database_password
  DB_HOST: localhost
