# api-replicaset.yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - name: my-api
        image: gcr.io/google-samples/hello-app:1.0  # Replace with your API image
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: api-config
        - secretRef:
            name: api-secret
