# db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_USER: dXNlcm5hbWU=  # base64 encoded value for 'username'
  DB_PASS: cGFzc3dvcmQ=  # base64 encoded value for 'password'