apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - name: http
      port: 80
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1 
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: iyogita/demo-app:1.0
          env:
            - name: DB_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: connectionString
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-sec
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-sec
                  key: password
          ports:
            - name: http
              containerPort: 8080

---