# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: your-docker-repo/api:latest
        ports:
          - containerPort: 5000
        envFrom:
          - configMapRef:
              name: api-config
          - secretRef:
              name: api-secret
